# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  input:          GFM

# Permalinks
permalink:        pretty

# Setup
title:            Data Visualization for Plant Pathologist
description:      'Teaching plant pathologists data visualization tools to show off their awesome science'
url:              http://Vegpathology.github.io/phyto-data-viz/
baseurl:          /phyto-data-viz
email:            pcvgt@ufl.edu
feedbackurl:      docs.google.com/forms/d/1y35uJukuZ9MPKQWWqw0Y8R4VOiaOtFJezDY_t_kJfTs/
author:
  name:           'Nicholas Dufault & James Fulton'

github:
  repo:           https://github.com/Vegpathology/phyto-data-viz
  #               Be sure the 'Issues' feature is activated in 'Settings'
